### PR TITLE
👷 :construction_worker: Fail on rc Versions in Master

### PR DESCRIPTION
**Pull request by Paulomart**
## What did you change?

The build now fails if the version is a rc version

## How can others test the changes?

n/a

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.)
- [x] I've merged the `develop` branch into my branch before finishing this PR.
- [x] I've **not added any other changes** than the ones described above.
- [x] I've mentioned all **PRs, which relate to this one**

### CODE REVIEW

**Comment by Paulomart** [comment]
Note that with this setup Jenkins will never ever publish rc versions again. Maybe we should allow publishing rc versions from some branches?

**Comment by heikomat** [comment]
@Paulomart we should definitely allow publishing rc-versions, but not from the master-branch an not without `--tag`

**Comment by Paulomart** [comment]
@heikomat That was my idea, the question is from which branches? Does Jenkins try to publish any RC? What happens if the publish fails?

**Comment by heikomat** [comment]
@Paulomart i'd suggest either develop, or we define a branch for that. If it fails, it fails, just like it does now. I don't see a problem there

**Pull request merged**
